var name4;
var name3 = null;
var name1 = "squirrel";
document.writeln(name);
console.log(name);
console.log(name2);
var name2 = name1;
debugger;
name1 = 27;
console.log(name1);
console.log(name2);
console.log(typeof name1);
console.log(typeof name2);
console.log(typeof name3);
console.log(typeof name4);
